-- Insert sample todo items
INSERT INTO TODO_ITEMS (TITLE, DESCRIPTION, COMPLETED, PRIORITY, DUE_DATE, CREATED_AT, UPDATED_AT)
VALUES ('Complete project documentation', 'Write comprehensive documentation for the Todo API project', 0, 5, SYSTIMESTAMP + INTERVAL '7' DAY, SYSTIMESTAMP, SYSTIMESTAMP);

INSERT INTO TODO_ITEMS (TITLE, DESCRIPTION, COMPLETED, PRIORITY, DUE_DATE, CREATED_AT, UPDATED_AT)
VALUES ('Fix UI bugs', 'Address the UI bugs reported in the frontend application', 0, 8, SYSTIMESTAMP + INTERVAL '2' DAY, SYSTIMESTAMP, SYSTIMESTAMP);

INSERT INTO TODO_ITEMS (TITLE, DESCRIPTION, COMPLETED, PRIORITY, DUE_DATE, CREATED_AT, UPDATED_AT)
VALUES ('Review pull requests', 'Review and provide feedback on pending pull requests', 1, 7, SYSTIMESTAMP - INTERVAL '1' DAY, SYSTIMESTAMP - INTERVAL '2' DAY, SYSTIMESTAMP - INTERVAL '1' DAY);

INSERT INTO TODO_ITEMS (TITLE, DESCRIPTION, COMPLETED, PRIORITY, DUE_DATE, CREATED_AT, UPDATED_AT)
VALUES ('Prepare for demo', 'Prepare slides and setup environment for the upcoming demo', 0, 9, SYSTIMESTAMP + INTERVAL '3' DAY, SYSTIMESTAMP, SYSTIMESTAMP);

INSERT INTO TODO_ITEMS (TITLE, DESCRIPTION, COMPLETED, PRIORITY, DUE_DATE, CREATED_AT, UPDATED_AT)
VALUES ('Update dependencies', 'Update project dependencies to the latest versions', 1, 4, SYSTIMESTAMP - INTERVAL '3' DAY, SYSTIMESTAMP - INTERVAL '4' DAY, SYSTIMESTAMP - INTERVAL '3' DAY);

INSERT INTO TODO_ITEMS (TITLE, DESCRIPTION, COMPLETED, PRIORITY, DUE_DATE, CREATED_AT, UPDATED_AT)
VALUES ('Implement search functionality', 'Add search functionality to the application', 0, 6, SYSTIMESTAMP + INTERVAL '5' DAY, SYSTIMESTAMP, SYSTIMESTAMP);

INSERT INTO TODO_ITEMS (TITLE, DESCRIPTION, COMPLETED, PRIORITY, DUE_DATE, CREATED_AT, UPDATED_AT)
VALUES ('Write unit tests', 'Increase test coverage with additional unit tests', 0, 7, SYSTIMESTAMP + INTERVAL '4' DAY, SYSTIMESTAMP, SYSTIMESTAMP);

INSERT INTO TODO_ITEMS (TITLE, DESCRIPTION, COMPLETED, PRIORITY, DUE_DATE, CREATED_AT, UPDATED_AT)
VALUES ('Deploy to production', 'Deploy the latest changes to the production environment', 0, 10, SYSTIMESTAMP + INTERVAL '10' DAY, SYSTIMESTAMP, SYSTIMESTAMP);

INSERT INTO TODO_ITEMS (TITLE, DESCRIPTION, COMPLETED, PRIORITY, DUE_DATE, CREATED_AT, UPDATED_AT)
VALUES ('Create user documentation', 'Write user guides and API documentation', 0, 5, SYSTIMESTAMP + INTERVAL '8' DAY, SYSTIMESTAMP, SYSTIMESTAMP);

INSERT INTO TODO_ITEMS (TITLE, DESCRIPTION, COMPLETED, PRIORITY, DUE_DATE, CREATED_AT, UPDATED_AT)
VALUES ('Code review', 'Perform code review for the recent changes', 1, 6, SYSTIMESTAMP - INTERVAL '2' DAY, SYSTIMESTAMP - INTERVAL '3' DAY, SYSTIMESTAMP - INTERVAL '2' DAY);

COMMIT;
